baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Creation To Revelation'
primary: true
siteGroup: 236e28e3-e3b7-489f-a8b9-cd980d3356fe # Creation To Revelation
sortOrder: 1
